id: P007924
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG24613
  title: གསོ་རིག་དཔྱད་རྩོམ།
  author: ''
  volumes:
    1ce64e55a86b48cf97980bd493158969:
      image_group_id: I1KG26421
      title: Volume 1 of gso rig dpyad rtsom/
      volume_number: 1
      total_pages: 419
      base_file: v001.txt
