id: P007924
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24613
  title: གསོ་རིག་དཔྱད་རྩོམ།
  author: ''
  volumes:
    7ad14e41cb794405862b57ebaa0bf0c3:
      image_group_id: I1KG26421
      title: ''
      volume_number: 1
      total_pages: 419
ebook_metadata:
  title: གསོ་རིག་དཔྱད་རྩོམ།
  author: ''
  sku: P007924
  cover: cover.jpg
  layers:
  - pagination
